$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: diabetes-deployment-alt5
endpoint_name: diabetes-endpoint-alt3
model: azureml:diabetes-model:1
instance_type: Standard_DS2_v2
instance_count: 1
environment:
  name: AzureML-sklearn-1.0-ubuntu20.04-py38-cpu
  version: 57
