$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: diabetes-env
version: 3
image: mcr.microsoft.com/azureml/sklearn-1.0-ubuntu20.04-py38-cpu-inference:latest
conda_file: conda.yaml
description: Environment for diabetes prediction model
