name: Code checks

on:
  pull_request:

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Use Python version 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Downgrade pip to 24.0
      run: python -m pip install pip==24.0
    - name: Install Flake8
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
###        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/

  test:
    name: Unit tests with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run pytest
        run: |
          pytest tests/

        
